name: Snake Contribution Graph
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Vector3451
          outputs: |
            dist/snake.svg?color_snake=00B4D8&color_dots=#0d1117,#003b5c,#006994,#0097c7,#00B4D8
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg || true
          git commit -m "Update snake contribution graph [skip ci]" || true
          git push
