name: Generate Space Shooter Contribution Game
on:
  schedule:
    - cron: "0 0 * * *" # Run at midnight daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Space Shooter
        uses: czl9707/github-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: Vector3451
          output-path: space-shooter.gif
          strategy: random

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add space-shooter.gif || true
          git commit -m "Auto-generate Space Shooter Contribution Graph [skip ci]" || true
          git push
